apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    service: nginx
spec:
  selector:
    matchLabels:
      service: nginx
  template:
    metadata:
      labels:
        service: nginx
    spec:
      containers:
      - name: nginx
        image: gcr.io/pf-msa-labo/kadonome-nginx
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 200m
